### ISSUE TITLE
ModuleNotFoundError: No module named 'colors'

### ISSUE THREAD

**Issue by zook111** [CrisSherban/BrainPad#2]
Traceback (most recent call last):
  File "training.py", line 10, in <module>
    from dataset_tools import split_data, standardize, load_data, preprocess_raw_eeg, ACTIONS
  File "E:\GIT\MyBrainHack\dataset_tools.py", line 5, in <module>
    from colors import red, green
ModuleNotFoundError: No module named 'colors'

Have tried pip install colour , pip install --user colour-science , pip install colored, pip install colours, pip install colors

**Comment by CrisSherban** [comment]
Hey there @zook111 ! 
It's an old package that I was using to have different colors in the terminal. I'm planning a code cleaning and a shared Pipenv for the project.
Meanwhile, I'll remove the "colors" stuff and re-push a version without it so you don't have to install it, give me a couple of minutes. 

Cris

> Traceback (most recent call last): File "training.py", line 10, in from dataset_tools import split_data, standardize, load_data, preprocess_raw_eeg, ACTIONS File "E:\GIT\MyBrainHack\dataset_tools.py", line 5, in from colors import red, green ModuleNotFoundError: No module named 'colors'
> 
> Have tried pip install colour , pip install --user colour-science , pip install colored, pip install colours, pip install colors

**Comment by krishnakinnal** [comment]
If you need to use the `colors` package in the future, the pip package is actually called `ansicolors`: -

```
pip3 install ansicolors
```
