### ISSUE TITLE
ValueError: could not broadcast input array from shape (8,250) into shape (8,)

### ISSUE THREAD

**Issue by GeneralDarwinz** [CrisSherban/BrainPad#3]
**Describe the bug**

Hi CrisSherban,

First, thank you very much for the code you shared here.
I'am trying to use my own openBCI headset to test how well CNN works.

So, i've recorded some data from : Acquire_eeg.py

Then i've tried to use training.py (even before the preprocessing.py because i wanted to see if everything worked before going deep into preprocessing ect)

But, training.py is calling Dataset_tools.py wich as a function named "load_data"

Load data seems to make a tensor from all the files I've in the personnal_data folder. (with shape [8,250,9])

but the return np.array(X), np.array(y) seems to see X as a list with shape [8]

returning the following error : ValueError: could not broadcast input array from shape (8,250) into shape (8,)

Is there something that i'am missing ?

Thank you very much,

Cheers,
Kevin Lopez

**Comment by CrisSherban** [comment]
Hey Kevin,
I planned to repurpose the repo into a pytorch-based one rewriting it from scratch, but unfortunately, I had many other projects along the way, and I never managed.
I hope you have found a way to use it.

Cheers, 
Cris
